### ISSUE TITLE
Too many progress bars on resizing command window size in Windows 10

### ISSUE THREAD

**Issue by VaibhavN007** [coderick14/stanford-dl#3]
Resizing window horizontally so that the progress bar gets wrapped to new line produces the multiple progress bars for the same downloading file
![stanford_dl](https://user-images.githubusercontent.com/18723079/32897186-ec1e609e-cb0a-11e7-9524-997bfd090c7c.PNG)

**Comment by coderick14** [comment]
Hey. Unfortunately, this is an issue with the progressbar library itself. [Check this out](https://github.com/gosuri/uiprogress/issues/3). Btw, thanks for using it. Feel free to contribute on anything that you can come up with.

**Comment by coderick14** [comment]
I'll close this issue for now. Until they fix their bug, or I find a new progress bar library.
